name: CI

on: [push]

jobs:
  tests:
    name: Run PHP Testes and Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Mysql 8 ⚙️
        run: |
              echo -e "Enable LOAD DATA LOCAL INFILE in my.cnf\n"
              echo -e "SETTING secure-file-priv TO EMPTY STRING\n"
              echo -e "[mysqld]\nsecure-file-priv=''" | sudo tee -a /etc/mysql/my.cnf
              echo -e "SETTING local_infile TO ON\n"
              echo -e "[mysqld]\nlocal_infile='ON'" | sudo tee -a /etc/mysql/my.cnf
              echo -e "Start MYSQL service, it is off by default\n"
              sudo systemctl enable mysql.service
              sudo systemctl start mysql.service
              echo -e "Creating Laravel Database\n"
              mysql --host 127.0.0.1 -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS testing;'
              echo -e "Check new settings\n"
              mysql --host 127.0.0.1 -uroot -proot -e "SELECT @@global.secure_file_priv, @@global.local_infile"

      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none


      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run Migrations 💾
        run: php artisan migrate --force -v

      - name: Run tests
        run: php artisan test

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --no-progress --no-interaction --ansi

      - name: Run Laravel Pint
        run: ./vendor/bin/pint
